/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(uploadCleanUp)'}/catagories` | `/catagories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(uploadCleanUp)'}/uploadScreen` | `/uploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(uploadCleanUp)'}/catagories` | `/catagories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(uploadCleanUp)'}/uploadScreen` | `/uploadScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/addScreen${`?${string}` | `#${string}` | ''}` | `/addScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profileScreen${`?${string}` | `#${string}` | ''}` | `/profileScreen${`?${string}` | `#${string}` | ''}` | `${'/(uploadCleanUp)'}/catagories${`?${string}` | `#${string}` | ''}` | `/catagories${`?${string}` | `#${string}` | ''}` | `${'/(uploadCleanUp)'}/uploadScreen${`?${string}` | `#${string}` | ''}` | `/uploadScreen${`?${string}` | `#${string}` | ''}` | `/screens/postPage${`?${string}` | `#${string}` | ''}` | `/screens/postScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(uploadCleanUp)'}/catagories` | `/catagories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(uploadCleanUp)'}/uploadScreen` | `/uploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
