/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/glassCeramic`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/medicalWaste`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/metal`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/paper`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/plastic`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/processedWood`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/tire`; params?: Router.UnknownInputParams; } | { pathname: `/screens/catagories`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/uploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/glassCeramic`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/medicalWaste`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/metal`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/paper`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/plastic`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/processedWood`; params?: Router.UnknownOutputParams; } | { pathname: `/catagoryScreens/tire`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/catagories`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/uploadScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/addScreen${`?${string}` | `#${string}` | ''}` | `/addScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profileScreen${`?${string}` | `#${string}` | ''}` | `/profileScreen${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/glassCeramic${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/medicalWaste${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/metal${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/paper${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/plastic${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/processedWood${`?${string}` | `#${string}` | ''}` | `/catagoryScreens/tire${`?${string}` | `#${string}` | ''}` | `/screens/catagories${`?${string}` | `#${string}` | ''}` | `/screens/postPage${`?${string}` | `#${string}` | ''}` | `/screens/postScreen${`?${string}` | `#${string}` | ''}` | `/screens/uploadScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addScreen` | `/addScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profileScreen` | `/profileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/glassCeramic`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/medicalWaste`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/metal`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/paper`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/plastic`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/processedWood`; params?: Router.UnknownInputParams; } | { pathname: `/catagoryScreens/tire`; params?: Router.UnknownInputParams; } | { pathname: `/screens/catagories`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/postScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/uploadScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
